[package]
name = "bevy_audio_analyser"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.0", features = ["wav"] }
uuid = "1.16.0"
kira = "0.7.3"
hound = "3.4"
rustfft = "5.1"